name: CI Rspec
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: recruiter_api_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/recruiter_api_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Install postgres client dependencies
        run: sudo apt-get install libpq-dev

      - name: Create database
        run: |
          bundle exec rails db:drop || true
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec spec --format documentation
